#!/bin/bash

WINDOW_X=300
WINDOW_Y=100
WINDOW_WIDTH=600
WINDOW_HEIGHT=450

ICON_SIZE=120

APP_ICON_X=120
APP_ICON_Y=250
APPLICATIONS_X=450
APPLICATIONS_Y=250

BACKGROUND_COLOR="#ffffff"
TEXT_COLOR="#333333"
ACCENT_COLOR="#007AFF"
SECONDARY_COLOR="#666666"

APP_TITLE="UnplugBlock"
APP_SUBTITLE="Automatic protection for your Mac"
DRAG_TEXT="Drag here"

SHOW_GRADIENT=true
SHOW_LOGO_WATERMARK=false
CORNER_RADIUS=15
SHOW_DROP_SHADOW=true

ARROW_STYLE="➡️"
ARROW_SIZE=80
SHOW_GRID_GUIDES=false

DMG_FORMAT="UDZO"
COMPRESSION_LEVEL=9
FILESYSTEM="HFS+"

echo "Configuration loaded from dmg-config.sh"
